# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2018, 12, 1)),
        ),
    ]
