# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
