# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20181201_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', height_field=200, upload_to='profilepics/%Y/%m/%d/', width_field=200),
        ),
    ]
