# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_addcourserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourserequest',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Instructor'),
        ),
        migrations.AlterField(
            model_name='addcourserequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Student'),
        ),
    ]
